### ISSUE TITLE
Missing semantic versioning

### ISSUE THREAD

**Issue by adriandmitroca** [SebastianPozoga/PHP-AllegroApi#3]
Your package has missing [semantic versioning](http://semver.org/) which causes issues with Composer:

`$ composer require SebastianPozoga/PHP-AllegroApi --dev`
`[InvalidArgumentException]
  Could not find package SebastianPozoga/PHP-AllegroApi at any version for yo
  ur minimum-stability (stable). Check the package spelling or your minimum-s
  tability`

**Comment by SebastianPozoga** [comment]
I refresh repository. Should be much better now. Use sebastianpozoga/php-allegroapi as name. To include a code as dependency you should create composer frame project. 

I was crerated example project. Clone https://github.com/SebastianPozoga/PHP-AllegroApi-EmptyProject

next install dependencies by:

```
composer install
```

and run by console:

```
php index.php
```

I am hope it help you :-)

**Comment by adriandmitroca** [comment]
Thank you! :)
