### ISSUE TITLE
sessionHandle

### ISSUE THREAD

**Issue by juhacz** [SebastianPozoga/PHP-AllegroApi#5]
Nie jestem jakimś mega wprawionym programistą, ale czy czasami klasa nie powinna mieć pola publicznego "sessionHandle", które zwraca "sessionHandlePart" sesji po zalogowaniu, tak aby wykonując jakikolwiek inne metody w danym skrypcie móc się posługiwać tym hashem? Przecież muszę go podawać wywołując inne metody chociażby doGetMySellItems, więc skąd mam go znać?
Dzięki za info.,

**Comment by j4r3kb** [comment]
Id sesji jest tworzone w $this->request po wywołaniu metody logowania, przy wywoływaniu innych metod parametry są dokładane do $this->request, czyli id sesji jest przekazywane za każdym razem, nawet kiedy nie jest wymagane przez api ;)

**Comment by SebastianPozoga** [comment]
@j4r3kb  true story bro ;-) Dokładnie tak to działa.
